// Definiciones de indicadores y datos por ciudad — fuente única de verdad
// Importado por scripts/seed.js y api/seed.js

const BASE_INDICATORS = [
  // ── FRONTERA (20%) ──
  { id: 1,  dim: 'Frontera', ind: 'Volumen Comercio Transfronterizo',
    tipo: 'pos', ref: 500,
    form: 'V_com = Σ (Exp + Imp)',
    vars: '<b>V_com:</b> Volumen de comercio transfronterizo.<br><b>Exp:</b> Valor de exportaciones (USD).<br><b>Imp:</b> Valor de importaciones (USD).',
    desc: 'Millones de USD por año. Valor total del comercio formal en el paso fronterizo.' },

  { id: 2,  dim: 'Frontera', ind: 'Flujo Migratorio Formal',
    tipo: 'pos', ref: 3000000,
    form: 'F_mig = Σ Cruces_reg',
    vars: '<b>F_mig:</b> Flujo migratorio formal.<br><b>Cruces_reg:</b> Tránsitos validados por puestos de control migratorio.',
    desc: 'Número de cruces de frontera registrados formalmente por año.' },

  { id: 3,  dim: 'Frontera', ind: 'Tasa Informalidad Migrante',
    tipo: 'neg', ref: 60,
    form: 'Inf = (P_inf / P_mig_act) * 100',
    vars: '<b>Inf:</b> Tasa de informalidad.<br><b>P_inf:</b> Migrantes trabajando sin contrato.<br><b>P_mig_act:</b> Población migrante económicamente activa.',
    desc: 'Porcentaje de migrantes en situación de empleo informal.' },

  { id: 4,  dim: 'Frontera', ind: 'Trazabilidad Biométrica',
    tipo: 'pos', ref: 10,
    form: 'T_bio = (P_bio / P_ctrl) * 10',
    vars: '<b>T_bio:</b> Índice de trazabilidad.<br><b>P_bio:</b> Puestos con biometría activa.<br><b>P_ctrl:</b> Puestos fronterizos totales.',
    desc: 'Puntos de control equipados con sistemas biométricos para registro.' },

  { id: 5,  dim: 'Frontera', ind: 'Plataformas Comercio Digital',
    tipo: 'pos', ref: 5,
    form: 'P_dig = Σ Apps_Aduanas',
    vars: '<b>P_dig:</b> Plataformas digitales activas.<br><b>Apps_Aduanas:</b> Sistemas VUCE o aduanas web operativas en frontera.',
    desc: 'Plataformas digitales activas para facilitar intercambio comercial.' },

  { id: 6,  dim: 'Frontera', ind: 'Migrantes con PPT Digital',
    tipo: 'pos', ref: 100,
    form: 'PPT = (M_ppt / M_tot) * 100',
    vars: '<b>PPT:</b> Permiso de Protección Temporal.<br><b>M_ppt:</b> Migrantes regularizados.<br><b>M_tot:</b> Total de migrantes censados.',
    desc: 'Porcentaje de migrantes con permiso de protección temporal activo.' },

  // ── ECONOMÍA (17%) ──
  { id: 7,  dim: 'Economía', ind: 'Empresas Unicornio',
    tipo: 'pos', ref: 2,
    form: 'U_val = Startups ≥ $10^9 USD',
    vars: '<b>U_val:</b> Empresas Unicornio locales.<br><b>$10^9 USD:</b> Valorización de mercado igual o mayor a 1 billón de dólares.',
    desc: 'Startups con valor de mercado igual o mayor a USD 1.000 millones.' },

  { id: 8,  dim: 'Economía', ind: 'Facilidad abrir empresa (Ranking)',
    tipo: 'neg', ref: 50,
    form: 'R_biz = Posición_Global',
    vars: '<b>R_biz:</b> Ranking Doing Business o equivalente.<br><b>Posición_Global:</b> Puesto exacto en el escalafón mundial (1 al 190).',
    desc: 'Posición global en facilidad para hacer negocios (menor es mejor).' },

  { id: 9,  dim: 'Economía', ind: 'Índice Global Ecosistemas Startup',
    tipo: 'neg', ref: 200,
    form: 'Rank_eco = Puesto_Mundial',
    vars: '<b>Rank_eco:</b> Startup Ecosystem Benchmark.<br><b>Puesto_Mundial:</b> Ranking de la ciudad a nivel global de ecosistemas tecnológicos.',
    desc: 'Posición de la ciudad en el ranking global de ecosistemas startup.' },

  { id: 10, dim: 'Economía', ind: 'Startups Tecnológicas Activas',
    tipo: 'pos', ref: 20,
    form: 'S_act = Σ Emp_TIC_validas',
    vars: '<b>S_act:</b> Startups activas.<br><b>Emp_TIC_validas:</b> Empresas de base tecnológica facturando u operando.',
    desc: 'Startups con producto validado y operando en el mercado.' },

  { id: 11, dim: 'Economía', ind: 'Comercio Electrónico (%)',
    tipo: 'pos', ref: 40,
    form: 'E_com = (V_web / V_tot) * 100',
    vars: '<b>E_com:</b> Adopción de E-commerce.<br><b>V_web:</b> Empresas que usan canales digitales.<br><b>V_tot:</b> Empresas registradas en Cámara de Comercio.',
    desc: 'Empresas que realizan ventas por canales digitales.' },

  { id: 12, dim: 'Economía', ind: 'Inversión en I+D+TIC (% PIB)',
    tipo: 'pos', ref: 2,
    form: 'I_D = (Inv_tech / PIB) * 100',
    vars: '<b>I_D:</b> Inversión en I+D+i.<br><b>Inv_tech:</b> Capital destinado a innovación.<br><b>PIB:</b> Producto Interno Bruto del municipio.',
    desc: 'Porcentaje del PIB local destinado a innovación y tecnología.' },

  // ── CAPITAL HUMANO (16%) ──
  { id: 13, dim: 'Capital Humano', ind: 'Población con Educ. Superior (%)',
    tipo: 'pos', ref: 80,
    form: 'E_sup = (P_grad / P_tot) * 100',
    vars: '<b>E_sup:</b> Educación superior/técnica.<br><b>P_grad:</b> Personas con título post-secundaria.<br><b>P_tot:</b> Población en edad de estudiar/trabajar.',
    desc: 'Proporción de la población con educación secundaria y superior.' },

  { id: 14, dim: 'Capital Humano', ind: 'Total Escuelas',
    tipo: 'pos', ref: 500,
    form: 'Esc = Σ (Públicas + Privadas)',
    vars: '<b>Esc:</b> Inventario escolar.<br><b>Públicas/Privadas:</b> Instituciones educativas formales georeferenciadas.',
    desc: 'Cantidad de escuelas públicas y privadas mapeadas en la ciudad.' },

  { id: 15, dim: 'Capital Humano', ind: 'Gasto Privado en Educación (USD)',
    tipo: 'pos', ref: 800,
    form: 'G_edu = Σ G_hogares / Pob',
    vars: '<b>G_edu:</b> Gasto per cápita en educación.<br><b>G_hogares:</b> Inversión familiar anual.<br><b>Pob:</b> Habitantes de la ciudad.',
    desc: 'Gasto privado anual en educación per cápita estimado en USD.' },

  { id: 16, dim: 'Capital Humano', ind: 'Laboratorios TIC en Escuelas',
    tipo: 'pos', ref: 60,
    form: 'Lab_tic = (Esc_lab / Esc_tot) * 100',
    vars: '<b>Lab_tic:</b> Laboratorios de tecnología.<br><b>Esc_lab:</b> Colegios con salas de cómputo o robótica.<br><b>Esc_tot:</b> Total de colegios.',
    desc: 'Colegios con salas dotadas de computadores o robótica (%).' },

  { id: 17, dim: 'Capital Humano', ind: 'Conectividad Escolar (%)',
    tipo: 'pos', ref: 100,
    form: 'C_esc = (Esc_net / Esc_tot) * 100',
    vars: '<b>C_esc:</b> Conectividad escolar.<br><b>Esc_net:</b> Instituciones con internet de banda ancha dedicado.',
    desc: 'Instituciones educativas con conexión a internet activa.' },

  { id: 18, dim: 'Capital Humano', ind: 'Brecha Digital Estudiantil (%)',
    tipo: 'neg', ref: 5,
    form: 'B_dig = (Est_0_pc / Est_tot) * 100',
    vars: '<b>B_dig:</b> Brecha digital.<br><b>Est_0_pc:</b> Estudiantes en hogares que no poseen computador ni tablet.',
    desc: 'Estudiantes sin computador ni tablet en casa (%).' },

  // ── COHESIÓN SOCIAL (16%) ──
  { id: 19, dim: 'Cohesión Social', ind: 'Ciudad Amigable con Mujeres',
    tipo: 'pos', ref: 4.5,
    form: 'C_amig = x̄(Índices_seguridad)',
    vars: '<b>C_amig:</b> Puntuación de ciudad amigable/segura.<br><b>x̄:</b> Media aritmética de encuestas cualitativas internacionales.',
    desc: 'Score de 1 a 5 de entorno amigable y seguro para mujeres.' },

  { id: 20, dim: 'Cohesión Social', ind: 'Total Hospitales y Clínicas',
    tipo: 'pos', ref: 50,
    form: 'Hosp = Σ Centros_salud',
    vars: '<b>Hosp:</b> Infraestructura de salud en la ciudad.<br><b>Centros_salud:</b> Clínicas y hospitales prestando servicio continuo.',
    desc: 'Infraestructura de salud incluyendo centros de salud locales.' },

  { id: 21, dim: 'Cohesión Social', ind: 'Tasa de Criminalidad',
    tipo: 'neg', ref: 30,
    form: 'Crimen = (Delitos / 100k_hab)',
    vars: '<b>Crimen:</b> Tasa delictiva/Percepción.<br><b>Delitos:</b> Denuncias formales ponderadas.<br><b>100k_hab:</b> Ratio poblacional estándar.',
    desc: 'Nivel general de crimen percibido (escala de 0 a 100).' },

  { id: 22, dim: 'Cohesión Social', ind: 'Hospitales con Telemedicina',
    tipo: 'pos', ref: 10,
    form: 'H_tele = (H_dig / Hosp) * 100',
    vars: '<b>H_tele:</b> Telemedicina habilitada.<br><b>H_dig:</b> Centros equipados para consultas remotas o diagnóstico virtual.',
    desc: 'Establecimientos que ofrecen consulta médica remota.' },

  { id: 23, dim: 'Cohesión Social', ind: 'Cobertura 4G/5G (%)',
    tipo: 'pos', ref: 100,
    form: 'Cob_4G = (A_4G / A_urb) * 100',
    vars: '<b>Cob_4G:</b> Cobertura de red celular.<br><b>A_4G:</b> Kilómetros cuadrados con señal móvil estable.<br><b>A_urb:</b> Perímetro urbano.',
    desc: 'Zona urbana con señal de telefonía móvil de alta velocidad (%).' },

  { id: 24, dim: 'Cohesión Social', ind: 'Apps Ciudadanas Activas',
    tipo: 'pos', ref: 5,
    form: 'Apps_gov = Σ Apps_Oficiales',
    vars: '<b>Apps_gov:</b> Participación ciudadana móvil.<br><b>Apps_Oficiales:</b> Aplicaciones de la Alcaldía en las tiendas de apps.',
    desc: 'Aplicaciones móviles oficiales con servicios activos para ciudadanos.' },

  // ── GOBERNANZA (16%) ──
  { id: 25, dim: 'Gobernanza', ind: 'Bitcoin Legal (0 o 1)',
    tipo: 'pos', ref: 1,
    form: 'Crypto = {0, 0.5, 1}',
    vars: '<b>Crypto:</b> Variable categórica de marco legal de criptomonedas.<br><b>0:</b> Ilegal. <b>0.5:</b> Tolerado/Gris. <b>1:</b> Marco regulatorio claro.',
    desc: 'Situación legal de criptoactivos (0.5 = Zona Gris / Tolerado).' },

  { id: 26, dim: 'Gobernanza', ind: 'Certificación ISO 37120',
    tipo: 'pos', ref: 4,
    form: 'ISO_37120 = Nivel (0..6)',
    vars: '<b>ISO_37120:</b> Estándar global de Smart Cities y calidad de vida.<br><b>Nivel:</b> Grado de certificación institucional obtenida.',
    desc: 'Nivel de certificación global para servicios urbanos y calidad de vida.' },

  { id: 27, dim: 'Gobernanza', ind: 'Trámites Digitales (%)',
    tipo: 'pos', ref: 70,
    form: 'T_dig = (T_web / T_tot) * 100',
    vars: '<b>T_dig:</b> Digitalización de burocracia.<br><b>T_web:</b> Trámites realizables sin asistencia presencial.',
    desc: 'Servicios del gobierno local que se pueden completar 100% online.' },

  { id: 28, dim: 'Gobernanza', ind: 'Datos Abiertos Alcaldía',
    tipo: 'pos', ref: 30,
    form: 'D_open = Σ Datasets_pub',
    vars: '<b>D_open:</b> Transparencia gubernamental.<br><b>Datasets_pub:</b> Archivos en formatos abiertos (CSV, JSON) en portal oficial.',
    desc: 'Conjuntos de datos (datasets) publicados oficialmente.' },

  { id: 29, dim: 'Gobernanza', ind: 'Cámaras Videovigilancia',
    tipo: 'pos', ref: 300,
    form: 'Cam_seg = Σ Cámaras_C4',
    vars: '<b>Cam_seg:</b> Videovigilancia urbana.<br><b>Cámaras_C4:</b> Cámaras tipo PTZ o LPR conectadas al centro de comando.',
    desc: 'Cámaras de seguridad operativas conectadas al centro de monitoreo.' },

  { id: 30, dim: 'Gobernanza', ind: 'Semáforos Inteligentes',
    tipo: 'pos', ref: 20,
    form: 'S_intel = (S_act / S_tot) * 100',
    vars: '<b>S_intel:</b> Semaforización adaptativa.<br><b>S_act:</b> Intersecciones con sensores de flujo de tráfico en tiempo real.',
    desc: 'Semáforos con control adaptativo al flujo vehicular en tiempo real.' },

  // ── MEDIO AMBIENTE (15%) ──
  { id: 31, dim: 'Medio Ambiente', ind: 'Calidad Agua Potable',
    tipo: 'pos', ref: 80,
    form: 'ICA = x̄(Var_químicas)',
    vars: '<b>ICA:</b> Índice de Calidad del Agua.<br><b>Var_químicas:</b> Mediciones promedio de pH, Turbidez, Cloro residual.',
    desc: 'Índice de 0 a 100 sobre la calidad percibida y real del agua.' },

  { id: 32, dim: 'Medio Ambiente', ind: 'Áreas Verdes (m²/hab)',
    tipo: 'pos', ref: 9,
    form: 'A_verde = Σ (m²_parq) / Pob',
    vars: '<b>A_verde:</b> Espacio verde per cápita.<br><b>m²_parq:</b> Área total de zonas arborizadas, reservas o parques urbanos.',
    desc: 'Metros cuadrados de área verde urbana disponible por persona.' },

  { id: 33, dim: 'Medio Ambiente', ind: 'Índice Calidad del Aire (AQI)',
    tipo: 'neg', ref: 10,
    form: 'AQI = max(I_PM2.5, I_PM10, I_O3)',
    vars: '<b>AQI:</b> Air Quality Index.<br><b>I_PM:</b> Sub-índices matemáticos correspondientes al mayor contaminante.',
    desc: 'Promedio anual de AQI. Menor valor indica aire más limpio.' },

  { id: 34, dim: 'Medio Ambiente', ind: 'Sensores IoT Calidad Aire',
    tipo: 'pos', ref: 15,
    form: 'S_iot = Σ Nodos_ESP32',
    vars: '<b>S_iot:</b> Densidad de sensores ambientales ciudadanos.<br><b>Nodos_ESP32:</b> Microcontroladores midiendo variables en tiempo real.',
    desc: 'Dispositivos de bajo costo instalados para medir contaminantes.' },

  { id: 35, dim: 'Medio Ambiente', ind: 'Sistemas Alerta Inundaciones',
    tipo: 'pos', ref: 5,
    form: 'A_inun = Σ Telemetría_río',
    vars: '<b>A_inun:</b> Alertas hidrológicas tempranas.<br><b>Telemetría_río:</b> Sensores de nivel del agua en ríos principales.',
    desc: 'Sensores en ríos con notificación automática de crecidas.' },

  { id: 36, dim: 'Medio Ambiente', ind: 'Energía Solar Instalada (MW)',
    tipo: 'pos', ref: 5,
    form: 'E_sol = Σ (MW_inst)',
    vars: '<b>E_sol:</b> Capacidad de transición energética.<br><b>MW_inst:</b> Megavatios generados por paneles solares interconectados a la red.',
    desc: 'Capacidad de generación solar en techos públicos y parques.' }
];

const CITY_DATA = {
  cucuta: {
    1:  { val: 320,       fuente: 'DIAN' },
    2:  { val: 12775000,  fuente: 'Migración Colombia' },
    3:  { val: 78,        fuente: 'DNP' },
    4:  { val: 4,         fuente: 'Migración Colombia' },
    5:  { val: 3,         fuente: 'DIAN / MinTIC' },
    6:  { val: 80,        fuente: 'Migración Colombia' },
    7:  { val: 0,         fuente: 'CB Insights' },
    8:  { val: 67,        fuente: 'World Bank' },
    9:  { val: 640,       fuente: 'StartupBlink' },
    10: { val: 5,         fuente: 'iNNpulsa' },
    11: { val: 15,        fuente: 'CC Cúcuta' },
    12: { val: 0.5,       fuente: 'DNP' },
    13: { val: 43,        fuente: 'DANE' },
    14: { val: 483,       fuente: 'OpenStreetMap' },
    15: { val: 148,       fuente: 'DANE' },
    16: { val: 15,        fuente: 'Comp. para Educar' },
    17: { val: 90,        fuente: 'Comp. para Educar' },
    18: { val: 35,        fuente: 'DANE' },
    19: { val: 2.5,       fuente: 'Nomad List' },
    20: { val: 18,        fuente: 'OpenStreetMap' },
    21: { val: 68,        fuente: 'Numbeo' },
    22: { val: 3,         fuente: 'MinSalud' },
    23: { val: 95,        fuente: 'MinTIC' },
    24: { val: 2,         fuente: 'Alcaldía Cúcuta' },
    25: { val: 0.5,       fuente: 'Banco República' },
    26: { val: 0,         fuente: 'WCCD' },
    27: { val: 30,        fuente: 'Alcaldía Cúcuta' },
    28: { val: 12,        fuente: 'Datos.gov.co' },
    29: { val: 150,       fuente: 'Policía Cúcuta' },
    30: { val: 5,         fuente: 'Sec. Movilidad' },
    31: { val: 55,        fuente: 'Numbeo / SSPD' },
    32: { val: 3.2,       fuente: 'Plan Desarrollo' },
    33: { val: 45,        fuente: 'IQAir' },
    34: { val: 3,         fuente: 'Jesús Álvarez' },
    35: { val: 1,         fuente: 'IDEAM' },
    36: { val: 1.2,       fuente: 'UPME' }
  },

  // Crisis económica e institucional venezolana
  sanantonio: {
    1:  { val: 60,        fuente: 'SENIAT (est.)' },
    2:  { val: 820000,    fuente: 'SAIME (est.)' },
    3:  { val: 92,        fuente: 'INE Venezuela (est.)' },
    4:  { val: 1,         fuente: 'SAIME (est.)' },
    5:  { val: 0,         fuente: 'SENIAT (est.)' },
    6:  { val: 10,        fuente: 'SAIME (est.)' },
    7:  { val: 0,         fuente: 'CB Insights' },
    8:  { val: 188,       fuente: 'World Bank' },
    9:  { val: 1850,      fuente: 'StartupBlink (est.)' },
    10: { val: 0,         fuente: 'Inapyme (est.)' },
    11: { val: 3,         fuente: 'CCIAST (est.)' },
    12: { val: 0.05,      fuente: 'ONCTI (est.)' },
    13: { val: 32,        fuente: 'INE Venezuela (est.)' },
    14: { val: 98,        fuente: 'OpenStreetMap' },
    15: { val: 12,        fuente: 'INE Venezuela (est.)' },
    16: { val: 3,         fuente: 'Min. Educación VE (est.)' },
    17: { val: 18,        fuente: 'CONATEL (est.)' },
    18: { val: 82,        fuente: 'INE Venezuela (est.)' },
    19: { val: 1.2,       fuente: 'Numbeo (est.)' },
    20: { val: 3,         fuente: 'OpenStreetMap' },
    21: { val: 88,        fuente: 'Numbeo (est.)' },
    22: { val: 0,         fuente: 'MPPS (est.)' },
    23: { val: 28,        fuente: 'CONATEL (est.)' },
    24: { val: 0,         fuente: 'Alcaldía SATS (est.)' },
    25: { val: 0.5,       fuente: 'BCV (est.)' },
    26: { val: 0,         fuente: 'WCCD' },
    27: { val: 5,         fuente: 'Alcaldía SATS (est.)' },
    28: { val: 1,         fuente: 'Datos.gob.ve (est.)' },
    29: { val: 8,         fuente: 'PNB Táchira (est.)' },
    30: { val: 0,         fuente: 'IAHULA (est.)' },
    31: { val: 18,        fuente: 'Numbeo (est.)' },
    32: { val: 1.5,       fuente: 'Alcaldía SATS (est.)' },
    33: { val: 32,        fuente: 'IQAir (est.)' },
    34: { val: 0,         fuente: 'N/A' },
    35: { val: 0,         fuente: 'INAMEH (est.)' },
    36: { val: 0.05,      fuente: 'Min. Energía VE (est.)' }
  },

  // Frontera con Ecuador (puente Rumichaca), 2 900 msnm → aire muy limpio
  ipiales: {
    1:  { val: 175,       fuente: 'DIAN Nariño (est.)' },
    2:  { val: 1480000,   fuente: 'Migración Colombia' },
    3:  { val: 65,        fuente: 'DNP (est.)' },
    4:  { val: 3,         fuente: 'Migración Colombia' },
    5:  { val: 2,         fuente: 'DIAN / MinTIC' },
    6:  { val: 55,        fuente: 'Migración Colombia (est.)' },
    7:  { val: 0,         fuente: 'CB Insights' },
    8:  { val: 73,        fuente: 'World Bank' },
    9:  { val: 920,       fuente: 'StartupBlink (est.)' },
    10: { val: 3,         fuente: 'iNNpulsa (est.)' },
    11: { val: 12,        fuente: 'CC Ipiales (est.)' },
    12: { val: 0.3,       fuente: 'DNP (est.)' },
    13: { val: 38,        fuente: 'DANE' },
    14: { val: 182,       fuente: 'OpenStreetMap' },
    15: { val: 118,       fuente: 'DANE (est.)' },
    16: { val: 12,        fuente: 'Comp. para Educar' },
    17: { val: 75,        fuente: 'Comp. para Educar' },
    18: { val: 45,        fuente: 'DANE (est.)' },
    19: { val: 2.2,       fuente: 'Numbeo (est.)' },
    20: { val: 8,         fuente: 'OpenStreetMap' },
    21: { val: 52,        fuente: 'Numbeo (est.)' },
    22: { val: 1,         fuente: 'MinSalud (est.)' },
    23: { val: 82,        fuente: 'MinTIC (est.)' },
    24: { val: 1,         fuente: 'Alcaldía Ipiales (est.)' },
    25: { val: 0.5,       fuente: 'Banco República' },
    26: { val: 0,         fuente: 'WCCD' },
    27: { val: 20,        fuente: 'Alcaldía Ipiales (est.)' },
    28: { val: 8,         fuente: 'Datos.gov.co (est.)' },
    29: { val: 85,        fuente: 'Policía Nariño (est.)' },
    30: { val: 2,         fuente: 'Sec. Tránsito Ipiales (est.)' },
    31: { val: 60,        fuente: 'Numbeo / SSPD (est.)' },
    32: { val: 4.5,       fuente: 'Plan Desarrollo Ipiales' },
    33: { val: 18,        fuente: 'IQAir (est.)' },
    34: { val: 1,         fuente: 'Iniciativa local (est.)' },
    35: { val: 0,         fuente: 'IDEAM (est.)' },
    36: { val: 0.3,       fuente: 'UPME (est.)' }
  },

  // Triple frontera Colombia–Brasil–Perú, entorno amazónico
  leticia: {
    1:  { val: 22,        fuente: 'DIAN Amazonas (est.)' },
    2:  { val: 245000,    fuente: 'Migración Colombia (est.)' },
    3:  { val: 70,        fuente: 'DNP (est.)' },
    4:  { val: 2,         fuente: 'Migración Colombia (est.)' },
    5:  { val: 1,         fuente: 'DIAN / MinTIC (est.)' },
    6:  { val: 38,        fuente: 'Migración Colombia (est.)' },
    7:  { val: 0,         fuente: 'CB Insights' },
    8:  { val: 73,        fuente: 'World Bank' },
    9:  { val: 1100,      fuente: 'StartupBlink (est.)' },
    10: { val: 1,         fuente: 'iNNpulsa (est.)' },
    11: { val: 8,         fuente: 'CC Amazonas (est.)' },
    12: { val: 0.2,       fuente: 'DNP (est.)' },
    13: { val: 28,        fuente: 'DANE' },
    14: { val: 46,        fuente: 'OpenStreetMap' },
    15: { val: 78,        fuente: 'DANE (est.)' },
    16: { val: 8,         fuente: 'Comp. para Educar (est.)' },
    17: { val: 65,        fuente: 'Comp. para Educar (est.)' },
    18: { val: 55,        fuente: 'DANE (est.)' },
    19: { val: 2.8,       fuente: 'Numbeo (est.)' },
    20: { val: 4,         fuente: 'OpenStreetMap' },
    21: { val: 32,        fuente: 'Numbeo (est.)' },
    22: { val: 1,         fuente: 'MinSalud (est.)' },
    23: { val: 62,        fuente: 'MinTIC (est.)' },
    24: { val: 1,         fuente: 'Alcaldía Leticia (est.)' },
    25: { val: 0.5,       fuente: 'Banco República' },
    26: { val: 0,         fuente: 'WCCD' },
    27: { val: 15,        fuente: 'Alcaldía Leticia (est.)' },
    28: { val: 5,         fuente: 'Datos.gov.co (est.)' },
    29: { val: 28,        fuente: 'Policía Amazonas (est.)' },
    30: { val: 0,         fuente: 'N/A' },
    31: { val: 65,        fuente: 'SSPD (est.)' },
    32: { val: 8.0,       fuente: 'SINCHI (est.)' },
    33: { val: 12,        fuente: 'IQAir (est.)' },
    34: { val: 2,         fuente: 'SINCHI / IDEAM (est.)' },
    35: { val: 2,         fuente: 'IDEAM (est.)' },
    36: { val: 0.5,       fuente: 'UPME (est.)' }
  },

  // Frontera Venezuela–Brasil, Brasil legalizó crypto 2022, gov.br digitalizado
  pacaraima: {
    1:  { val: 14,        fuente: 'Receita Federal (est.)' },
    2:  { val: 385000,    fuente: 'Polícia Federal (est.)' },
    3:  { val: 80,        fuente: 'IBGE (est.)' },
    4:  { val: 3,         fuente: 'Polícia Federal (est.)' },
    5:  { val: 1,         fuente: 'Receita Federal (est.)' },
    6:  { val: 48,        fuente: 'ACNUR Brasil (est.)' },
    7:  { val: 0,         fuente: 'CB Insights' },
    8:  { val: 124,       fuente: 'World Bank' },
    9:  { val: 1200,      fuente: 'StartupBlink (est.)' },
    10: { val: 0,         fuente: 'SEBRAE (est.)' },
    11: { val: 10,        fuente: 'SEBRAE (est.)' },
    12: { val: 0.1,       fuente: 'MCTI Brasil (est.)' },
    13: { val: 25,        fuente: 'IBGE (est.)' },
    14: { val: 16,        fuente: 'OpenStreetMap' },
    15: { val: 195,       fuente: 'IBGE (est.)' },
    16: { val: 15,        fuente: 'MEC Brasil (est.)' },
    17: { val: 70,        fuente: 'MEC Brasil (est.)' },
    18: { val: 50,        fuente: 'IBGE (est.)' },
    19: { val: 2.3,       fuente: 'Numbeo (est.)' },
    20: { val: 2,         fuente: 'OpenStreetMap' },
    21: { val: 48,        fuente: 'Numbeo (est.)' },
    22: { val: 1,         fuente: 'Min. Saúde Brasil (est.)' },
    23: { val: 55,        fuente: 'ANATEL (est.)' },
    24: { val: 1,         fuente: 'Pref. Pacaraima (est.)' },
    25: { val: 1,         fuente: 'Banco Central do Brasil' },
    26: { val: 0,         fuente: 'WCCD' },
    27: { val: 35,        fuente: 'gov.br (est.)' },
    28: { val: 10,        fuente: 'dados.gov.br (est.)' },
    29: { val: 14,        fuente: 'PC Roraima (est.)' },
    30: { val: 0,         fuente: 'N/A' },
    31: { val: 48,        fuente: 'FUNASA (est.)' },
    32: { val: 6.0,       fuente: 'IBGE (est.)' },
    33: { val: 22,        fuente: 'IQAir (est.)' },
    34: { val: 1,         fuente: 'INPA (est.)' },
    35: { val: 1,         fuente: 'ANA Brasil (est.)' },
    36: { val: 0.8,       fuente: 'ANEEL (est.)' }
  }
};

function buildIndicators(cityKey) {
  const cityVals = CITY_DATA[cityKey];
  return BASE_INDICATORS.map(base => ({
    ...base,
    val:    cityVals[base.id].val,
    fuente: cityVals[base.id].fuente
  }));
}

const CITIES = [
  { name: 'Cúcuta',                country: 'Colombia',   flag: '🇨🇴', population: 750000, region: 'Norte de Santander', indicators: buildIndicators('cucuta') },
  { name: 'San Antonio del Táchira', country: 'Venezuela', flag: '🇻🇪', population: 150000, region: 'Estado Táchira',      indicators: buildIndicators('sanantonio') },
  { name: 'Ipiales',               country: 'Colombia',   flag: '🇨🇴', population: 122000, region: 'Nariño',              indicators: buildIndicators('ipiales') },
  { name: 'Leticia',               country: 'Colombia',   flag: '🇨🇴', population: 45000,  region: 'Amazonas',            indicators: buildIndicators('leticia') },
  { name: 'Pacaraima',             country: 'Brasil',     flag: '🇧🇷', population: 18000,  region: 'Roraima',             indicators: buildIndicators('pacaraima') }
];

module.exports = { BASE_INDICATORS, CITY_DATA, buildIndicators, CITIES };
